name: coverage.py badge
description: Generate a coverage.py badge
author: tj-actions
inputs:
  output:
    description: 'Output path to write the coverage badge.'
    required: false
    default: 'coverage.svg'
  overwrite:
    description: 'Overwrite an existing coverage badge.'
    required: false
    default: 'true'
  working-directory:
    description: 'Current working directory'
    required: false
    default: '.'
  install_cmd:
    description: 'Command to install coverage-badge (pip or uv)'
    required: false
    default: 'pip install'

runs:
  using: 'composite'
  steps:
    - id: coverage-badge
      working-directory: ${{ inputs.working-directory }}
      run: |
        ${{ inputs.install_cmd }} -U setuptools coverage-badge
        
        EXTRA_ARGS=""

        if [[ '${{ inputs.overwrite }}' == 'true'  ]]; then
          EXTRA_ARGS+="-f"
        fi

        coverage-badge $EXTRA_ARGS -o "${{ inputs.output }}"
      shell: bash
branding:
  icon: check-circle
  color: white
